GET http://localhost:5000/api



###


POST http://localhost:5000/newuser
Content-Type: application/json

{
    "username" : "Shane",
    "password" :  "tsitsikama"
}

###


POST http://localhost:5000/login
Content-Type: application/json

{
    "username" : "Brodie",
    "password" :  "asdf"
}